version: '3'

services:

  app:
    build: ./api
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: mongodb://admin:password@mongo:27017
    command: ./pokeapp -port=8080

  mongodb:
    image: mongo:6.0.3
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-volume:/app/db